name: publish-tests

on: [workflow_dispatch]

jobs:
  publish_tests:
    runs-on: ubuntu-latest
    name: publish tests
    steps:
      - name: do the thing
        uses: mavriksc/publish-tests@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          bucket-name: scar-jjrb
          path-tests: reports
          publisher-setup: false
