name: publish-tests

on: [workflow_dispatch]

jobs:
  publish_tests:
    runs-on: ubuntu-latest
    name: publish tests
    steps:
      - name: do the thing
        uses: mavriksc/publish-tests@master
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          ref_name: ${{ github.ref_name}}
          repository: ${{ github.repository}}
          bucket-name: scar-jjrb
          path-tests: /home/runner/work/jus-messin/jus-messin/reports
          publisher-setup: false
