name: publish-tests

on: [workflow_dispatch]

jobs:
  publish_tests:
    runs-on: ubuntu-latest
    name: publish tests
    steps:
      - name: do the thing
        uses: mavriksc/publish-tests@master
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS }}
          ref_name: ${{ github.ref_name}}
          repository: ${{ github.repository}}
          bucket_name: scar-jjrb
          path_tests: reports
          publisher_setup: false
