name: test database

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.18-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: 🕵️‍♀️Who did what
        run: |
          echo Hello, ${{ github.actor }}
          
      - name: 🧙‍♂️Create database
        run: |
          PGPASSWORD=postgres psql -U postgres -p 5432 -h localhost -tc "SELECT 'CREATE DATABASE mydb' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mydb')"


      - name: ✅ Verify database
        run: |
          PGPASSWORD=postgres psql -U postgres -p 5432 -h localhost -tc "SELECT 1 WHERE EXISTS (SELECT FROM pg_database WHERE datname = 'mydb')"
