name: test database

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.18-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: 🕵️‍♀️Who did what
        run: |
          echo Hello, ${{ github.actor }}
          
      - name: 🧙‍♂️Create database
        run: |
          PGPASSWORD=postgres psql -U postgres -p 5432 -h localhost -f scripts/init_test_dbs.sql


      - name: ✅ Verify database
        run: |
          PGPASSWORD=postgres psql -U postgres -p 5432 -h localhost -d a_test -tc "CREATE TABLE accounts (user_id serial PRIMARY KEY, username VARCHAR ( 50 ) UNIQUE NOT NULL, password VARCHAR ( 50 ) NOT NULL, email VARCHAR ( 255 ) UNIQUE NOT NULL, created_on TIMESTAMP NOT NULL, last_login TIMESTAMP);"
